languageCode = 'zh'
title = '乳圖鑑'
enableInlineShortcodes = true
theme =["simplog","hugo-shortcode-gallery"]

baseURL = "https://kancollebra.netlify.app"

galleryLoadJQuery = true

[params]
  subtitle = "Bra Size Comparison"
  colorTheme = "default"
  description = "This is a simple blog theme for Hugo."
  twitter = "GoHugoIO"
  customCSS = ""
  adobeFontsKitId = ""

  [params.enabled]
    comment = true
    summary = true
    toc = true
