languageCode = 'zh'

title = '乳圖鑑'

enableInlineShortcodes = true

theme =["simplog","hugo-shortcode-gallery"]

baseURL = "/"

relativeURLs = true

uglyURLs = true

galleryLoadJQuery = true

[params]
  subtitle = "Bra Size Comparison"
  colorTheme = "default"
  description = "Bra size comparison of ship girls."
  twitter = "ivon852"
  customCSS = ""
  adobeFontsKitId = ""
  [params.enabled]
    comment = true
    summary = true
    toc = true
